### PR TITLE
Add ds18b20

### PR DESCRIPTION
**Pull request by matze**
Adds infrastructure for temperature sensors as well as a wrapper for the DS18B20.

### CODE REVIEW

**Comment by matze** [comment]
- [ ] update `README.md` regarding the `configure` script

**Comment by maximweb** [comment]
> It did not compile with the other one? Or flash?

Sorry, I should have been more precise in my commit message. Under WSL everything except upload works (see #11) with the default `avrdude.conf` path. On OS X, however, the file resides solely in the `Arduino.app` dir.

Regarding the hardcoded board limitation, I opt for a more flexible solution. Even I have several nano boards, some with old some with new bootloader. This changes the required BOARD_SUB.

I am willing to implement it but I see a chicken and egg problem: The valid boards used by Arduino.mk are derived from the `boards.txt` file somewhere in the IDE `../../hardware/arduino/avr/boards.txt` and they are easily accessible using `make show_boards` and `make show_submenu`, but those commands are only accessible after `configure` ran. Hence, I would have to extract them manually from `boards.txt`.

**Comment by maximweb** [comment]
`configure `now reads supported boards from Arduino IDE's `boards.txt`. It can now be called using
`./configure [options] <BOARD>.[<SUBTYPE>]`
If a combination is not available, the valid list if (sub)types is listed.

It works for me on OS X and WSL.

**Review by maximweb — APPROVED** [review]

**Comment by maximweb** [comment]
So are we done here for now? @matze merge?

**Comment by matze** [comment]
Yep!

**Pull request merged**
