### PR TITLE
Add clang format file and CI check

### PR DESCRIPTION
**Pull request by matze**

### CODE REVIEW

**Comment by matze** [comment]
@maximweb not sure you want this sign off. Should certainly prevent annoying comments from me :laughing:

**Comment by maximweb** [comment]
> @maximweb not sure you want this sign off. Should certainly prevent annoying comments from me 😆

I'm sure you will come up with new ideas, distracting me from the relevant work.
Btw, except for 1-2 trailing whitespaces, I meticulously stuck to the style you used in your libs. At least before doing this.

**Comment by matze** [comment]
I was also not following it 100% as far as I can see from the reformatting, so having it been checked by some objective authority is a win-win. Not sure which editor you use, but most IDEs should be able to integrate clang-format. If not you can just run `clang-format -e *.cpp` from the command-line.

**Comment by maximweb** [comment]
> I was also not following it 100% as far as I can see from the reformatting, so having it been checked by some objective authority is a win-win. Not sure which editor you use, but most IDEs should be able to integrate clang-format. If not you can just run `clang-format -e *.cpp` from the command-line.

I only have a favorite IDE for python, so I switched editors and platforms all the time. Now I give vscode a try. At least it does the formatting for me.

**Pull request merged**
